### ISSUE TITLE
Var error

### ISSUE THREAD

**Issue by gmartha07** [imperavi/superkube#1]
Hi
I have encountered an error in the color function.

.card {
background-color: color (card, background);
}

In the html is returning:

.card {
background-color: --c-card- background
}

There is a "space" between the card and the background.
The correct thing would be to stay
--c-card-background

**Comment by imperavi** [comment]
Hi,

Unfortunately, I do not see it happening in our example. Superkube builds the correct variable name: https://github.com/imperavi/superkube/blob/master/example-project/css/main.css.

Perhaps it is something else, for example, in your variables somehow the name of the color is specified with a space

**Comment by gmartha07** [comment]
Hi
Using Laravel Mix trying to compile the scss this error occurs.

I identified where the problem is.
It is in the "to-string" function.

To work properly, just change it to look like this:

```
// list to string
@function to-string($list, $glue: "", $is-nested: false) {
  $result : null;
  
  @for $i from 1 through length($list) {
	$e : nth($list, $i);
	
	@if type-of($e) == list {
	  $result : $result#{to-string($e, $glue, true)};
	} @else {
	  $result : if(
		  $i != length($list) or $is-nested,
		  #{$result}#{$e}#{$glue}, #{$result}#{$e} //change this line
	  );
	}
  }
  @return $result;
}
```

**Comment by imperavi** [comment]
Thanks. Fixed!
