### ISSUE TITLE
Active menu links does not have the cursor set to pointer?

### ISSUE THREAD

**Issue by jorqensen** [imperavi/superkube#10]
Is there any design reason that menu links active state do not have `cursor: pointer;` on by default?

It's a bit confusing/misleading from a UX standpoint, that an active state on a link will prompt you the cursor that indicates text selection instead of `cursor: pointer;` - like menu items usually have.

I'll gladly PR it, but if there's a good reason to as why it's like this, please do tell. 🙂

**Comment by imperavi** [comment]
I was a little confused by this. Just from the point of view of common sense and good UX, the active item should not be clickable and all its appearance should show that it is not necessary to click. Such an item displays the current state of the screen and clicking on it shouldn't lead to anything.

Ideally, when the link ('a' tag) of the active item is replaced by a span tag, to indicate exactly that it's not a link, but an indication of the current state.

**Comment by jorqensen** [comment]
I see what you mean.

So your suggestion is that the active item should be replaced with a `span` tag when active? It feels a bit cumbersome to change the markup according to the state of an item, rather than just applying a class to it based on a criteria.

IMO a lot of websites let you re-request the same page regardless if it's active or not, see example on [About Google](https://about.google/) - Regardless what page you are on and it has an active state, it's still clickable with the cursor set to a pointer, indicating that this is indeed clickable.

Obviously this is easily modified by changing the Sass (or simply just adding a inline style when active). My argument was more that this seems more as expected behavior, than the current default. No?

**Comment by imperavi** [comment]
Thank you very much for this discussion. On second thought, I think I will agree. In the next update we will remove the 'cursor: text' property of all menu modules.

**Comment by jorqensen** [comment]
Awesome! Thanks a lot for the prompt response.
