### ISSUE TITLE
Superkube isn't generating palettes correctly when color names match CSS colors

### ISSUE THREAD

**Issue by michaellenaghan** [imperavi/superkube#12]
Out of the box, Superkube's generated palette look like this:

```scss
    --palette-#000: #030612;
    --palette-#fff: #fff;
    ...
    --palette-#ff0-darker: #9F7E04;
    --palette-#ff0-dark: #ECC01E;
    --palette-#ff0-base: #F9C918;
    --palette-#ff0-mid: #FBDF74;
    --palette-#ff0-light: #FDE9A3;
    --palette-#ff0-lighter: #FEF7DD;
    --palette-#ff0-lightest: #FEFCF3;
    ...
    --palette-#fff-5: rgba(255, 255, 255, 0.05);
    --palette-#fff-7: rgba(255, 255, 255, 0.07);
    --palette-#fff-10: rgba(255, 255, 255, 0.1);
    --palette-#fff-15: rgba(255, 255, 255, 0.15);
    --palette-#fff-20: rgba(255, 255, 255, 0.2);
    --palette-#fff-25: rgba(255, 255, 255, 0.25);
    --palette-#fff-30: rgba(255, 255, 255, 0.3);
    --palette-#fff-40: rgba(255, 255, 255, 0.4);
    --palette-#fff-50: rgba(255, 255, 255, 0.5);
    --palette-#fff-60: rgba(255, 255, 255, 0.6);
    --palette-#fff-70: rgba(255, 255, 255, 0.7);
    --palette-#fff-80: rgba(255, 255, 255, 0.8);
    --palette-#fff-90: rgba(255, 255, 255, 0.9);
    --palette-#fff-95: rgba(255, 255, 255, 0.95);
    --palette-#000-5: rgba(3, 6, 18, 0.05);
    --palette-#000-7: rgba(3, 6, 18, 0.07);
    --palette-#000-10: rgba(3, 6, 18, 0.1);
    --palette-#000-15: rgba(3, 6, 18, 0.15);
    --palette-#000-20: rgba(3, 6, 18, 0.2);
    --palette-#000-25: rgba(3, 6, 18, 0.25);
    --palette-#000-30: rgba(3, 6, 18, 0.3);
    --palette-#000-40: rgba(3, 6, 18, 0.4);
    --palette-#000-50: rgba(3, 6, 18, 0.5);
    --palette-#000-60: rgba(3, 6, 18, 0.6);
    --palette-#000-70: rgba(3, 6, 18, 0.7);
    --palette-#000-80: rgba(3, 6, 18, 0.8);
    --palette-#000-90: rgba(3, 6, 18, 0.9);
    --palette-#000-95: rgba(3, 6, 18, 0.95);
```

Because the black and white palettes in particular are heavily used throughout the framework, this error creates a very poor out-of-the-box experience.

The problem is that CSS color names are being used as identifiers. As the Sass docs [say](https://sass-lang.com/documentation/values/strings), they're actually treated as color values:

> Heads up!
>
> Not all identifiers are parsed as unquoted strings:
>
> [CSS color names](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Color_keywords) are parsed as [colors](https://sass-lang.com/documentation/values/colors).

A temporary workaround — one that doesn't involve changing the original source code — is to redefine colors using quoted strings for names:

```scss
// =Basis
$opacity-colors: "white", "black";

// =Palette
$palette: map-extend($palette, (
    black: null,
    "black": #030612,
    white: null,
    "white": #ffffff,
    yellow: null,
    "yellow": (
        darker: #9F7E04,
        dark: #ECC01E,
        base: #F9C918,
        mid: #FBDF74,
        light: #FDE9A3,
        lighter: #FEF7DD,
        lightest: #FEFCF3
    ),
));
```

Those changes fix *almost* all of the problems. Three syntactically incorrect vars are still generated though:

```scss
    --palette-#000: #030612;
    --palette-#fff: #fff;
    ...
    --palette-#ff0:;
```

That's because `$value` isn't checked for `null` [here](https://github.com/imperavi/superkube/blob/52258a441298183c1e4b1b764b17c8df9dd998cb/superkube/mixins/generators.scss#L21). (If you look a few lines down you'll see that `$color` gets checked for `null` when the opacity color vars are generated.)

(`palette-dark.scss` has similar problems, but I don't currently have dark mode enabled.)

**Comment by michaellenaghan** [comment]
Here's a better workaround that gets rid of the three problem values:

```sass
// =Palette
$palette: map-extend(map-remove($palette, black, white, yellow), (
    "black": #030612,
    "white": #ffffff,
    "yellow": (
        darker: #9F7E04,
        dark: #ECC01E,
        base: #F9C918,
        mid: #FBDF74,
        light: #FDE9A3,
        lighter: #FEF7DD,
        lightest: #FEFCF3
    ),
));
```

**Comment by jamieg270** [comment]
I'm not the developer of SuperKube however I'm not getting that css output when processing the scss. I'm using Dart with Codekit to output the css if that helps.

I do get the following warning/s for the use of white, black, green etc. color names:

WARNING: You probably don't mean to use the color value green in interpolation here.
It may end up represented as green, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "green").
If you really want to use the color value here, use '"" + $name'.


Since the css is output correctly at my end I've just been ignoring the warning. Probably a dumb question but is your scss processor up to date?

**Comment by michaellenaghan** [comment]
OK, digging a bit further...

I *think* Zola is using version 3.6.4 of `libsass`. I don't know how old that is, but I do know that `libsass` was officially deprecated at some point in favour of Dart Sass. So documented or not, I think you're right: this was caused by old tooling.

I'll close the bug.

Thanks for asking the obvious question!
